export function renderAppTemplate(): string {
  return [
  '<div class="shell" data-active-tab="input">',
  '  <header class="header">',
  '    <div class="brand" aria-label="Lime"><img class="brand-logo" src="/logo.svg" alt="Lime" /></div>',
  '    <nav class="tabs" aria-label="Lime 功能">',
  '      <button class="tab is-active" type="button" data-tab="input">设置</button>',
  '      <button class="tab" type="button" data-tab="test">测试</button>',
  '      <button class="tab" type="button" data-tab="benchmark">评测</button>',
  '      <button class="tab" type="button" data-tab="dictionary">词库</button>',
  '      <button class="tab" type="button" data-tab="history">历史</button>',
  '      <button class="tab" type="button" data-tab="diagnostics">诊断</button>',
  '    </nav>',
  '    <span class="badge" data-service-state="unavailable" aria-live="polite">服务 不可用</span>',
  "  </header>",
  '  <div class="toast-region" data-notice-region aria-live="polite" aria-atomic="true">',
  '    <div class="notice is-hidden" data-notice role="status" aria-hidden="true">',
  '      <span data-notice-message></span>',
  '      <button class="toast-close" data-notice-close type="button" aria-label="关闭提示">×</button>',
  "    </div>",
  "  </div>",
  "  <main>",
  '    <section class="panel" data-panel="input">',
  '      <form data-config-form>',
  '        <section class="settings-section settings-section-first">',
  '          <div class="section-heading"><h3>前端</h3></div>',
  '          <div class="form-grid">',
  '            <label class="field"><span>每页展示候选词数</span><input data-config="page_size" type="number" min="1" max="20" required /></label>',
  '            <label class="field"><span>前文预览字符数</span><input data-config="context_preview_char_limit" type="number" min="0" max="1024" required /></label>',
  '            <label class="field"><span>前文实际获取字符数</span><input data-config="preceding_text_char_limit" type="number" min="1" max="4096" required /></label>',
  '            <label class="field"><span>管理界面深色模式</span><select data-theme-mode><option value="system">跟随系统</option><option value="light">固定浅色</option><option value="dark">固定深色</option></select></label>',
  '          </div>',
  '        </section>',
  '        <section class="settings-section">',
  '          <div class="section-heading"><h3>后端</h3></div>',
  '          <div class="form-grid">',
  '            <label class="field"><span>Rime 方案</span><select data-config="rime_schema"><option value="rime_ice">雾凇拼音（全拼）</option><option value="double_pinyin">自然码双拼</option><option value="double_pinyin_abc">智能 ABC 双拼</option><option value="double_pinyin_mspy">微软双拼</option><option value="double_pinyin_sogou">搜狗双拼</option><option value="double_pinyin_flypy">小鹤双拼</option><option value="double_pinyin_ziguang">紫光双拼</option><option value="double_pinyin_jiajia">拼音加加双拼</option></select></label>',
  '            <label class="field"><span>LLM 单次请求 token 数上限</span><input data-config="llm_context_token_limit" type="number" min="1" max="4096" required /></label>',
  '            <label class="field"><span>LLM 单次输入推理次数上限</span><input data-config="llm_inference_count_limit" type="number" min="1" max="32" required /></label>',
  '            <label class="field"><span>LLM 重排输入候选词数</span><input data-config="llm_rerank_count" type="number" min="1" max="128" required /></label>',
  '            <label class="field"><span>LLM 重排采纳候选词数</span><input data-config="llm_effective_count" type="number" min="1" max="32" required /></label>',
  '            <label class="field"><span>LLM 重排时忽略 Emoji</span><input data-config="llm_ignore_emoji" type="checkbox" /></label>',
  '            <label class="field"><span>LLM 后端</span><select data-config="llm_backend"><option value="cuda">CUDA</option><option value="cpu">CPU</option></select></label>',
  '          </div>',
  '        </section>',
  '        <div class="actions settings-actions"><button class="button button-primary" type="submit">保存设置</button></div>',
  '      </form>',
  '      <section class="settings-section model-status-section"><div class="section-heading"><h3>模型状态</h3><span class="status-dot" data-model-state>未加载</span></div>',
  '        <div class="model-card"><dl class="status-list"><dt>路径</dt><dd class="model-path" data-model-path title="—">—</dd><dt>文件大小</dt><dd data-model-size>—</dd><dt>推理路径</dt><dd data-model-scoring-path>—</dd></dl><div class="model-memory" data-model-memory><p class="muted">未加载模型，暂无显存占用信息。</p></div></div>',
  '      </section>',
  '      <section class="settings-section preset-section"><div class="section-heading"><h3>模型预设</h3><div class="section-heading-actions"><span class="meta-badge" data-preset-count>0 个</span><button class="button button-danger" data-unload-model type="button">卸载模型</button></div></div>',
  '        <div class="actions model-add-actions"><button class="button" data-add-model type="button" aria-expanded="false">添加模型</button></div>',
  '        <form class="preset-form is-hidden" data-preset-form><label class="field"><span>名称</span><input data-preset-name type="text" placeholder="例如 Qwen 7B" required /></label><label class="field field-wide"><span>GGUF 文件路径</span><input data-preset-path type="text" placeholder="C:\\Models\\lime.gguf" required /></label><div class="actions"><button class="button button-primary" type="submit">保存模型</button><button class="button" data-cancel-add-model type="button">取消</button></div></form>',
  '        <div class="preset-list" data-model-presets><p class="muted">尚未读取模型预设。</p></div>',
  '      </section>',
  '      <form class="model-form is-hidden" data-model-form><input data-model-path-input type="text" aria-hidden="true" tabindex="-1" /></form>',
  "    </section>",
  '    <section class="panel is-hidden" data-panel="test">',
  '      <form data-test-form>',
  '        <label class="field field-wide field-stacked"><span>上文</span><textarea data-test-context rows="3" placeholder="可选：输入光标前的中文文本"></textarea></label>',
  '        <label class="field field-wide"><span>拼音</span><input data-test-preedit type="text" placeholder="例如 nihao" required /></label>',
  '        <div class="actions"><button class="button button-primary" type="submit">请求候选</button><button class="button" data-test-clear type="button">清空结果</button></div>',
  "      </form>",
  '      <div class="test-result" data-test-result></div>',
  "    </section>",
  '    <section class="panel is-hidden" data-panel="benchmark">',
  '      <div class="panel-heading"><span class="meta-badge" data-benchmark-status>未开始</span></div>',
  '      <form data-benchmark-form>',
  '        <div class="benchmark-controls">',
  '          <div class="field field-wide"><span id="benchmark-model-label">模型</span><div class="benchmark-model-options" data-benchmark-models role="group" aria-labelledby="benchmark-model-label"><p class="muted">正在读取模型…</p></div></div>',
  '          <div class="field field-wide"><span id="benchmark-mode-label">拼音</span><div class="actions-inline" role="group" aria-labelledby="benchmark-mode-label"><label class="check-option"><input data-benchmark-mode type="checkbox" value="full" checked /><span>全拼</span></label><label class="check-option"><input data-benchmark-mode type="checkbox" value="initials" /><span>首拼</span></label></div></div>',
  '          <div class="field field-wide"><span>语料</span><div class="muted" data-benchmark-corpora>正在读取语料…</div></div>',
  '          <div class="benchmark-configurations" data-benchmark-configurations><div class="benchmark-configuration" data-benchmark-configuration><label class="field"><span>重排候选词数</span><input data-benchmark-rerank type="number" min="1" max="128" step="1" value="32" required /></label><label class="field"><span>前文字符数</span><input data-benchmark-context type="number" min="1" max="4096" step="1" value="128" required /></label><button class="button" data-benchmark-remove-configuration type="button" aria-label="移除配置" disabled>移除</button></div></div>',
  '          <div><button class="button" data-benchmark-add-configuration type="button">添加配置</button></div>',
  '        </div>',
  '        <div class="actions"><button class="button button-primary" data-benchmark-run type="submit">开始评测</button><button class="button button-danger" data-benchmark-stop type="button" disabled>停止</button><button class="button" data-benchmark-export type="button" disabled>导出 JSON</button></div>',
  '      </form>',
  '      <div class="benchmark-progress" data-benchmark-progress aria-live="polite"><div class="progress-track" role="progressbar" aria-label="评测进度" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0" data-benchmark-progress-track><span data-benchmark-progress-bar></span></div><div class="progress-meta"><span data-benchmark-progress-label>未开始</span><span class="mono" data-benchmark-progress-count>0%</span></div></div>',
  '      <div class="benchmark-summary" data-benchmark-summary><p class="muted">选择模型和配置后开始评测。</p></div>',
  '    </section>',
  '    <section class="panel is-hidden" data-panel="dictionary">',
  '      <div class="actions"><span class="meta-badge" data-dictionary-count>— 条</span><button class="button" data-import-dictionary type="button">导入 JSON</button><button class="button" data-export-dictionary type="button">导出 JSON</button><button class="button button-danger" data-clear-dictionary type="button">清空用户词库</button><input class="visually-hidden" data-dictionary-file type="file" accept="application/json,.json" /></div>',
  '      <div class="table-wrap"><table><thead><tr><th>拼音</th><th>文本</th><th>权重</th></tr></thead><tbody data-dictionary-table><tr><td colspan="3" class="muted">尚未读取词库</td></tr></tbody></table></div>',
  "    </section>",
  '    <section class="panel is-hidden" data-panel="history">',
  '      <div class="panel-heading"><h2>历史</h2><div class="actions-inline"><span class="meta-badge" data-history-count>0 条</span><button class="button button-danger" data-clear-history type="button">清空历史</button></div></div>',
  '      <div class="table-wrap"><table class="history-table"><thead><tr><th>上文</th><th>拼音</th><th>Rime 候选（前 2）</th><th>LLM 排序（前 2）</th><th>端到端用时</th><th>模型</th></tr></thead><tbody data-history-table><tr><td colspan="6" class="muted">暂无输入记录</td></tr></tbody></table></div>',
  '      <div class="pagination" data-history-pagination><button class="button" data-history-prev type="button">上一页</button><span data-history-page-label>第 1 页</span><button class="button" data-history-next type="button">下一页</button></div>',
  '      <section class="history-detail is-hidden" data-history-detail aria-live="polite"><div class="panel-heading compact-heading"><p class="muted" data-history-detail-meta>—</p><button class="button" data-history-detail-close type="button">返回列表</button></div><div data-history-detail-table><p class="muted">选择一条记录查看详情。</p></div></section>',
  "    </section>",
  '    <section class="panel is-hidden" data-panel="diagnostics">',
  '      <div class="panel-heading"><h2>诊断</h2><button class="button" data-refresh type="button">刷新</button></div>',
  '      <dl class="status-list diagnostics-list"><dt>服务状态</dt><dd data-diagnostic-state>—</dd><dt>模型</dt><dd data-diagnostic-model>—</dd><dt>词库条目</dt><dd data-diagnostic-dictionary>—</dd><dt>最近操作</dt><dd data-last-operation>—</dd></dl>',
  "    </section>",
  "  </main>",
  "</div>",
].join("\n");
}
